package com.avi.core;
// Generated Oct 13, 2008 12:26:54 AM by Hibernate Tools 3.2.0.beta8


/**
 * Symbol generated by hbm2java
 */
public class Symbol implements java.io.Serializable
{

    // Fields    

    private int id;
    private String name;
    private String exchange;

    // Constructors

    public String getExchange()
    {
        return exchange;
    }

    public void setExchange( String exchange )
    {
        this.exchange = exchange;
    }

    /**
     * default constructor
     */
    public Symbol()
    {
    }

    // Property accessors
    public int getId()
    {
        return this.id;
    }

    public void setId( int id )
    {
        this.id = id;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName( String name )
    {
        this.name = name;
    }
}


